### ISSUE TITLE
74HC86 not connected to vcc and gnd in "_Alternative PCB-Layout by Juergen"

### ISSUE THREAD

**Issue by cblank2** [MakerMeik/Window-Sensor#3]
in the "_Alternative PCB-Layout by Juergen" the 74HC86 has no power ;-(

pin 14 should be conntected to vcc
pin 7 should be connected to gnd

**Comment by MakerMeik** [comment]
You're right, something has obviously really gone wrong here. It is the alternative design of a viewer. Unfortunately, I had not final tested that and apparently neither had he.
Have you already ordered the PCBs or have you found the error before. If you already have the PCBs, you could try connecting the correct pins with enamelled copper wire.
However, I believe that the rest of the pins on the 74HC86 are not connected properly either. I think I will remove the entire folder from Github and limit myself to my own design, which I have tested in depth and which is successfully in use in quite a few places in my house.
Sorry for the trouble.

**Comment by cblank2** [comment]
Yes, i got some of the PCBs ;-(
i connected the missing pins with a simple copper wire and it seems to work

after i built my own 3d-printed case for it, i believe your original layout would fit better ;-(


I've a suggestion for the pcb: having another button on the board would not really raise complexity, but add some more flexibility for the "customer"
I made some other PCBs with an extra button, which will turn the "config-mode" on, if it's pressed during boot.
So a wifi-hotspot is enabled and you can make some settings via webserver (e.g. set wifi-config) or even upgrade the software
(just a thought)

**Comment by MakerMeik** [comment]
Thanks, that's a really interesting suggestion. I will consider this for my future projects. However, this project is finished for me, apart from bugs of course, if any are still found.
