### ISSUE TITLE
Version 2 PCB reduced size

### ISSUE THREAD

**Issue by gadjet** [MakerMeik/Window-Sensor#4]
Not an issue really just an update on my second revision of my PCB
https://github.com/gadjet/Window-Door-Sensor-V2
I also have another version in the works even smaller with a bit more functionality.

**Comment by teuchezh** [comment]
I wonder if your version is fully compatible with the version from this repository in terms of hardware (in the sense of components) and software?
In your version, does the battery connect directly or does it involve connecting a charging module, for example, the same TP4056?

**Comment by gadjet** [comment]
My version contains no charging circuitry, as I use ESP-NOW to transmit the data packet which doesn't require a connection to a router and only takes around 500mS to transmit therefore a 500mAh battery should last over a year depending on usage so I don't need the recharging capability.
The circuit is the same although the components are different as I use single gate ICs instead of a quad gate chip.

**Comment by MakerMeik** [comment]
I love your project! It's totally amazing and I didn't expect you to optimize it with such perseverance. I've already discovered the even further scaled down version 3 and I couldn't believe my eyes. Awesome!

**Comment by gadjet** [comment]
Thanks, I think I may have become addicted to  your window sensor 😁 I have a version 4 that has the position for a button and a bme280 I2C sensor for temp/humidity/pressure, I'm using version 3 to remotely monitor outside Temp.  It's been running for 3 weeks transmitimg every 15 mins and the battery has only dropped 0.1v
