### ISSUE TITLE
New Version 5 PCB

### ISSUE THREAD

**Issue by gadjet** [MakerMeik/Window-Sensor#5]
Hi,
Just thought I'd let you know version 5 is now working, small PCB with additional button trigger to be used as doorbell? or maybe vibration switch?
Quiescent now down to 3 to 5 uA depending on usage
![V5_Assembled](https://user-images.githubusercontent.com/1810366/160195244-c8266bc3-b8c5-4846-818d-3df988393448.jpg)

Details @ https://github.com/gadjet/Window-Door-sensor-Version-5

**Comment by MakerMeik** [comment]
It's so impressive where you've taken this project in the meantime. I've updated the Github- and Blog-links to your new version in my video description and can only hope that future viewers of the video will find this great evolution. Unbelivable!

In fact, I really need to do a follow up video on this. At the moment I unfortunately lack the time, but I think I will have your circuit manufactured in due course and rebuild. Your circuit is the perfect basis for all conceivable other battery-powered projects based on ESP8266. Thank you for sharing your work with the community.

**Comment by gadjet** [comment]
Thanks very much for the kind words, I really love making stuff and it's even better when others also find it useful.
I would be happy to send you a PCB if you like, if you are on Facebook I'm a member of the ESP8266/ESP32 group, join and then you can message me direct?
